languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://www.zhangxi.co/"
title = "Xi Zhang"
googleAnalytics = "G-JFC7CRM9K3"

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#fff"
colorPrimary = "#5489b6"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#5489b6"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#5489b6"
pages = 1
