baseURL = "https://www.zhangxi.co/"
languageCode = "en-us"
title = "Xi Zhang"
#theme = "awesome-identity"
#theme = "hugo-devresume-theme"
theme = "deepspace-xi"
publishDir = "docs"
staticDir = "static"

## Footer Configurations
[params.footer]
  copyright = "Xi Zhang"
  poweredBy = true

[params]
  author = "Xi Zhang"
  description = "Resume"
  primaryColor = "#5489B6"
  textPrimaryColor = "#292929"

  [params.profile]
    enable = true
    name = "Xi Zhang"
    tagline = "VP of Engineering / Inpensa Inc."
    avatar = "portrait-xi.png"

    [params.contact]
      enable = true
      location = "Greater New York"

      [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "career # zhangxi.co"
      [[params.contact.list]]
        icon = "fas fa-blog"
        url = "https://blog.zhangxi.co/"
        text = "blog.zhangxi.co"
      [[params.contact.list]]
        icon = "fas fa-file-alt"
        url = "/assets/XiZhang.pdf"
        text = "View in PDF"

    [params.sidebar]
      enable = false

    [params.skills]
      enable = false

      [[params.skills.list]]
      title = "Management"
          [[params.skills.list.items]]
          details = "Agile Methodologies"
          [[params.skills.list.items]]
          details = "Team player"
          [[params.skills.list.items]]
          details = "Strong problem solver"
          [[params.skills.list.items]]
          details = "Relationship Management"

      [[params.skills.list]]
      title = "Technical"
          [[params.skills.list.items]]
          details = "Well-Architected Framework"
          [[params.skills.list.items]]
          details = "Micro-Services Architecture / Serveless Architecture"
          [[params.skills.list.items]]
          details = "JavaScript / React / Node.JS"
          [[params.skills.list.items]]
          details = "Core Java / Enterprise Architecture"
          [[params.skills.list.items]]
          details = "Design and implement database structures"
          [[params.skills.list.items]]
          details = "Lead and deliver complex software systems"

      [params.education]
        enable = true

          [[params.education.list]]
          degree = "MSc in Computer Science"
          university = "University of San Francisco"
          dates = "2007 - 2009"
          [[params.education.list]]
          degree = "BSc in Mathematics and Applied Mathematics"
          university = "Peking University"
          dates = "2002 - 2006"

      [params.awards]
        enable = false

          [[params.awards.list]]
          name = "Award Lorem Ipsum"
          body = "Microsoft lorem ipsum"
          date = "2019"
          [[params.awards.list]]
          name = "Award Donec Sodales"
          body = "Oracle Aenean"
          date = "2017"

      [params.languages]
          enable = true

          [[params.languages.list]]
          name = "English"
          level = "Professional"
          [[params.languages.list]]
          name = "Chinese"
          level = "Native"

      [params.interests]
          enable = false

          [[params.interests.list]]
          name = "Climbing"
          [[params.interests.list]]
          name = "Snowboarding"
          [[params.interests.list]]
          name = "Photography"
          [[params.interests.list]]
          name = "Travelling"

      [params.summary]
          enable = false
          text = "Hands-on software architect and engineering leader with a strong academic background in both computer science and mathematics, with a proven track record of building and leading engineering teams in both established and startup environments and delivering quality products within a limited time frame.  Passionate and results-oriented problem solver with strong enthusiasm for programming and technology. "

      [params.experience]
          enable = true

          [[params.experience.list]]
          title = "V.P. of Engineering"
          dates = "Dec 2018 - Present"
          company = "Inpensa Inc."
          details = "As VP of Engineering, responsible for the technical leadership, product development, engineering efficiencies, and hosting operations of Inpensa's state-of-the-art SaaS-based Business Case Management solution. "
          [[params.experience.list.items]]
          details = "Launched the OnDemand platform with Predictable Analytics in 3 months, bringing enterprise customers domain knowledge to SMB customers, which attracted market attention, and boosted sales pipeline by 50%. "
          [[params.experience.list.items]]
          details = "Applied Agile methodologies to the whole team and built the CI/CD pipeline in a quarter, increased productivity by 35%, and reduced cycle time by 50% to two weeks."
          [[params.experience.list.items]]
          details = "Incorporated the Well-Architected Framework into the cloud operation process, archiving a 35% reduction in SaaS operating costs with 10% overall performance improvement."
          [[params.experience.list.items]]
          details = "Established and led a Security Work Group and achieved 100% security compliance for customers from various industries, including the heavily regulated Banking industry."
          [[params.experience.list.items]]
          details = "Successfully delivered end-to-end solutions that serve cross-function teams and integrate with various enterprise systems for 10+ large customers across major industries. "
          [[params.experience.list.items]]
          details = "Worked closely with other leadership team members to lead new product line developments and new market segment expansion, which significantly increased the company’s valuation."

          [[params.experience.list]]
          title = "Architect / Director of R&D"
          dates = "Mar. 2012 - Mar. 2018"
          company = "Inpensa Inc."
          details = ""
          [[params.experience.list.items]]
          details = "Architected the innovative 3-tier distributed platform with configuration-driven taxonomy and workflow framework, enabling entirely different appearances and workﬂows on the same codebase yet configurable by non-technical analysts."
          [[params.experience.list.items]]
          details = "Hired 30+ resources, and wove them into teams, empowered them to deliver high-quality products within a limited time frame."
          [[params.experience.list.items]]
          details = "Led the transition of the service tier to micro-services and server-less architecture, increased throughput by 60%, enabling monthly product release cycles."
          [[params.experience.list.items]]
          details = "Demonstrated technical flexibility during pre-sale client engagement by implementing a critical feature to meet business needs within 24 hours, resulting in signing the first deal with a Fortune 100 company."
          [[params.experience.list.items]]
          details = "Successfully launched five SaaS products in three years, made sales to five Fortune 500 enterprise customers, and attracting dozens of potential clients."

          [[params.experience.list]]
          title = "Software Engineer / Tech Lead"
          dates = "Jul. 2009 - Oct. 2011"
          company = "Cisco Systems"
          details = "Led a global located engineering team of 10 responsible for building the Real-Time Enterprise Business Intelligence Analysis and Visualization Platform at Cisco Advanced Services."

          [[params.experience.list.items]]
          details = "Led the design and implementation of the search based BI Services powered by a SOLR cluster, enabling enterprise customers to filter and search through historical data and generate real-time visualization reports based on result sets. "
          [[params.experience.list.items]]
          details = "As a pioneer in implementing Big Data for Enterprise BI Platform, scaled one of the earliest SOLR clusters in Silicon Valley from a single node to 50+ nodes to support the real-time analytics of billions of line items."
          [[params.experience.list.items]]
          details = "Enabled real-time search by reducing transaction locking time from minutes to within 10 seconds through a direct RAM index searcher."
          [[params.experience.list.items]]
          details = "Reduced real-time filter response time by 85% by implementing distributed object level caching."

    [params.projects]
          enable = false

          [[params.projects.list]]
          title = "Project Lorem Ipsum"
          meta = "Open Source"
          tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

          [[params.projects.list]]
          title = "Project Sed Fringilla"
          meta = "Open Source"
          tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

          [[params.projects.list]]
          title = "Project Praesent"
          meta = "Open Source"
          tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

      [params.information]
          enable = true

          [[params.information.list]]
          title = "Education"
          [[params.information.list.items]]
          details = "Computer Science, M.Sc · University of San Francisco · San Francisco, CA"
          [[params.information.list.items]]
          details = "Mathematics and Applied Mathematics, B.Sc · Peking University · Beijing, China"

      [params.social]
          enable = true

          [[params.social.list]]
          icon = "fab fa-github-square"
          url = "//github.com/zxi"
          title = "zxi"
          [[params.social.list]]
          icon = "fab fa-linkedin"
          url = "//linkedin.com/in/xi-zhang"
          title = "xi-zhang"
          [[params.social.list]]
          icon = "fab fa-twitter-square"
          url = "//twitter.com/zxi"
          title = "@zxi"
